# Generated by Django 4.2.5 on 2023-10-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stand',
        ),
    ]
