# Generated by Django 4.2.5 on 2023-10-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0002_alter_stand_valor'),
        ('reservas', '0002_delete_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='stand_key',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='stand.stand'),
            preserve_default=False,
        ),
    ]
