# Generated by Django 4.2.5 on 2023-10-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
